export const titleSuggestions = [
  "",
  "The Lost City",
  "Echoes of the Past",
  "The Secret of the Island",
  "Shadow of the Night",
  "The Edge of Tomorrow",
  "Whispers in the Wind",
  "The Last Stand",
  "The Forgotten Kingdom",
  "The Rise of the Phoenix",
  "The Final Countdown",
  "The Last Illusion",
  "The Curse of the Mummy",
  "The Illusionist",
  "The Dark Knight Returns",
  "The Legend of the Sword",
  "The Hunt for the Golden Crown",
  "The Rise of the Dragon",
];

export const artStyles = [
  "3D Illustration",
  "Anime",
  "Abstract",
  "Charcoal Drawing",
  "Crayon Drawing",
  "Digital Art",
  "Flat Art",
  "Ink Drawing",
  "Minimalism",
  "Pencil Drawing",
  "Paint Art",
  "Psychedelic",
  "Realism",
  "Surrealism",
  "Vector",
  "Vintage",
];

export const audiences = ["Children", "Teens", "Family", "Adults", "Seniors"];

export const genres = [
  "Action",
  "Adventure",
  "Comedy",
  "Crime",
  "Drama",
  "Fantasy",
  "Historical",
  "Horror",
  "Knowledge",
  "Mystery",
  "Mythology",
  "Nature",
  "Romance",
  "SciFi",
];

export const themes = [
  "Ancient",
  "Apocalyptic",
  "Contemporary",
  "Cyberpunk",
  "Dystopian",
  "Futuristic",
  "Medieval",
  "Modern",
  "Post-Apocalyptic",
  "Postmodern",
  "Prehistoric",
  "Renaissance",
  "Space Opera",
  "Steampunk",
  "Supernatural",
  "Technological",
  "Time Travel",
  "Tribal",
  "Urban",
  "Western",
  "Wild West",
  "19th Century Britain",
];
