export const types = [
  "Protagonist",
  "Antagonist",
  "Companion",
  "Follower",
  "Love Interest",
  "Side Kick",
  "Supporting Character",
];

export const arcs = [
  "Corruption",
  "Dillusionment",
  "Fall",
  "Positive Change",
  "Unchange",
];

export const personalities = [
  "Disciplined",
  "Hospitable",
  "Passionate",
  "Philosophical",
  "Simple",
  "Sentimental",
  "Socially Awakward",
  "Spontaneous",
  "Spunky",
  "Unconventional",
];

export const archetypes = [
  "Creator",
  "Explorer",
  "Hero",
  "Innocent",
  "Lover",
  "Magician",
  "Outlaw",
  "Ruler",
  "Sage",
];

export const nameSuggestions = [
  "",
  "Aria Shadowborn",
  "Balthazar Blackheart",
  "Caspian Stormchaser",
  "Daria Nightshade",
  "Ember Blaze",
  "Finn Dragonrider",
  "Gareth Thunderstrike",
  "Hazel Woodspirit",
  "Isaac Moonwhisper",
  "Jasmine Dreamweaver",
  "Kai Frostblade",
  "Landon Shadowstrike",
  "Mara Darkblade",
  "Niamh Starlight",
  "Odin Stormbringer",
  "Phoenix Fireheart",
  "Quinn Nightwing",
  "Rune Thunderclap",
  "Sable Shadowalker",
  "Tahlia Moonwhisper",
  "Ulric Frostfang",
  "Violet Stormchaser",
  "Wyatt Wildheart",
  "Xander Moonblade",
  "Yara Stormbringer",
  "Zara Dreamweaver",
  "Aurora Starlight",
  "Brynn Thunderstrike",
  "Cian Moonwhisper",
  "Drake Shadowalker",
  "Eirlys Woodspirit",
  "Fenris Frostfang",
  "Gwendolyn Dreamweaver",
  "Harrison Thunderclap",
  "Isolde Moonblade",
  "Jagger Shadowstrike",
  "Keira Stormchaser",
  "Lorcan Wildheart",
  "Mordecai Frostblade",
  "Niamh Starlight",
  "Odin Stormbringer",
  "Pascal Fireheart",
  "Quinn Nightwing",
  "Rune Thunderclap",
  "Sabine Shadowalker",
];

export const wantSuggestions = [
  "",
  "Magical powers",
  "Eternal youth",
  "A dragon's hoard of treasure",
  "The ability to fly",
  "Invisibility",
  "A unicorn as a companion",
  "A phoenix's immortality",
  "A genie's wish-granting abilities",
  "An ability to breathe underwater",
  "The power to control the elements",
  "A magical sword",
  "A talking animal companion",
  "A spell to become a vampire",
  "A potion of invincibility",
  "A magical portal to another world",
  "A time-traveling spell",
  "A shape-shifting ability",
  "A ghostly companion",
  "A magical teleportation ability",
];

export const needSuggestions = [
  "",
  "A clear goal or vision",
  "A plan or strategy",
  "Persistence and determination",
  "Self-discipline and self-motivation",
  "A positive attitude and mindset",
  "Support and encouragement from others",
  "Knowledge and skills relevant to their goal",
  "Flexibility and adaptability",
  "Confidence and self-belief",
  "Focus and concentration",
  "Time management and organization",
  "Willingness to learn and grow",
  "Resilience and ability to overcome setbacks",
  "Risk-taking and willingness to experiment",
  "Network and connections",
  "Resources such as money, equipment or facilities",
  "Emotional intelligence and ability to manage emotions",
  "Creativity and out-of-the-box thinking",
  "Collaboration and teamwork",
  "Good physical and mental health",
];

export const flawSuggestions = [
  "",
  "Lack of motivation or direction",
  "Fear of failure",
  "Procrastination",
  "Lack of discipline",
  "Limited mindset",
  "Negative self-talk",
  "Lack of support or resources",
  "Difficulty setting and achieving goals",
  "Limited problem solving skills",
  "Inability to manage time effectively",
  "Difficulty in prioritizing tasks",
  "Limited communication and interpersonal skills",
  "Difficulty in handling stress and pressure",
  "Inability to stay focused",
  "Lack of flexibility and adaptability",
  "Limited ability to learn from mistakes",
  "Difficulty in making decisions",
  "Limited ability to manage emotions",
  "Lack of self-confidence",
];
